"use client"; // Ensure this is at the very top of your Mailer component file

import React, { useRef, useState } from "react";
import ReCAPTCHA from "react-google-recaptcha";

export default function Mailer() {
  // 1. Create a reference element for the reCAPTCHA instance
  const recaptchaRef = useRef<ReCAPTCHA>(null);

  const [formData, setFormData] = useState({ name: "", email: "", message: "" });
  const [status, setStatus] = useState<string | null>(null);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus("Sending message...");

    // 2. Fetch the active token generated by the reCAPTCHA widget
    const token = recaptchaRef.current?.getValue();

    if (!token) {
      setStatus("Please verify that you are not a robot.");
      return;
    }

    try {
      // 3. Send the form values along with your verification token
      const response = await fetch("/api/email", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
          gRecaptchaToken: token, // Sent directly to your updated api/email/route.ts
        }),
      });

      const data = await response.json();

      if (response.ok) {
        setStatus(data.message || "Thanks! Email received. We shall contact you soon.");
        setFormData({ name: "", email: "", message: "" });
        
        // 4. Reset the captcha widget so it can be re-verified if needed
        recaptchaRef.current?.reset(); 
      } else {
        setStatus(data.error || "Verification failed. Please try again.");
        recaptchaRef.current?.reset();
      }
    } catch (error) {
      setStatus("A connection error occurred. Please try again.");
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-4 w-full">
      {/* 
         Keep your existing tailwind inputs here. Ensure their "name" 
         properties match your formData state keys ("name", "email", "message")
      */}
      <div>
        <label className="block font-semibold mb-1">Name</label>
        <input type="text" name="name" value={formData.name} onChange={handleChange} required className="w-full border p-2 rounded" />
      </div>
      
      <div>
        <label className="block font-semibold mb-1">Email</label>
        <input type="email" name="email" value={formData.email} onChange={handleChange} required className="w-full border p-2 rounded" />
      </div>

      <div>
        <label className="block font-semibold mb-1">Message</label>
        <textarea name="message" value={formData.message} onChange={handleChange} required className="w-full border p-2 rounded" rows={4} />
      </div>

      {/* 5. Inject the reCAPTCHA Box right above the submit button */}
      <div className="my-2">
        <ReCAPTCHA
          ref={recaptchaRef}
          sitekey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY || ""}
        />
      </div>

      <button type="submit" className="bg-red text-white p-3 rounded font-bold hover:opacity-90 transition-opacity">
        Submit Message
      </button>

      {status && <p className="text-sm font-semibold mt-1">{status}</p>}
    </form>
  );
}
